<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Fact;
use Fisharebest\Webtrees\Individual;
use Illuminate\Support\Collection;

/**
 * @var bool                 $can_edit
 * @var Collection<int,Fact> $notes_facts
 * @var Individual           $record
 */
?>

<!-- Name accordion -->
<div class="col-sm accordion" id="individual-names">
    <?php foreach ($record->facts(['NAME']) as $fact) : ?>
        <?= view('individual-page-name', ['fact' => $fact]) ?>
    <?php endforeach ?>

    <?php foreach ($record->facts(['SEX']) as $fact) : ?>
        <?= view('individual-page-sex', ['fact' => $fact]) ?>
    <?php endforeach ?>

    <?= view('individual-page-notes', ['can_edit' => $can_edit, 'facts' => $notes_facts, 'individual' => $record]) ?>
</div>
